"""GEE crop classification adapter.

Trains a RandomForest on a labeled FeatureCollection (generated by the
"作物时序特征提取" upstream algorithm), evaluates via
``errorMatrix`` (OA / Kappa / confusion matrix), classifies the full ROI,
and exports the result to a GEE Asset. The platform's background poller
then downloads the Asset back into the platform so the operator can
preview / download the GeoTIFF directly.

User-facing flow
---------------
  - GEE Project ID  (ee.Initialize)
  - target year
  - 研究区: 本地上传 / 已上传历史 / GEE Asset ID（三选一）
  - 特征文件: 本地上传 / 已上传历史 / GEE Asset ID（三选一）
  - 固定参数：树数 / DEM 范围 / min_values / max_values / 云量阈值 / 训练比例
    —— 由算法内置，不允许在前端修改（在表单里以只读 notice 形式展示）
  - 高级参数：任务名称 / num_trees / train_ratio / label_property / cloud_pct_max

Result (job.result) shape mirrors ``crop_features`` Pattern B:

    {
      "status": "submitted" → "completed",
      "result_type": "gee_task" → "raster",
      "files": [{"name": "<description>.tif", "label": "classification", ...}],
      "metrics": {
        "year": ...,
        "oa": ..., "kappa": ..., "confusion_matrix": [[...], ...],
        "num_trees": ..., "train_ratio": ...,
        "asset_id": ..., "output_tif_name": ...,
        "gee_task_id": ...,
        "cards": [{key, label, value, unit}, ...]
      }
    }
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from app.algorithms.base import AlgorithmAdapter, ProgressCallback
from app.algorithms.crop_classification import algorithm as crop_classification_algorithm
from app.algorithms.crop_classification import configs as cfg


class CropClassificationAdapter(AlgorithmAdapter):
    id = "crop_classification"
    name = "广西甘蔗分类--区域分类"
    type = "GEE"
    description = (
        "本算法基于 GEE 的 Sentinel-1/2 时序特征与 DEM，用随机森林对研究区进行作物分类，"
        "并自动导出分类结果 GeoTIFF 及精度指标"
    )

    params_schema = [
        # ===== 一、基础配置（用户输入）=====
        {
            "key": "gee_project_id",
            "label": "GEE 项目 ID",
            "type": "text",
            "required": True,
            "default": "sodium-ray-505904-i3",
            "hint": (
                "用于 ee.Initialize(project=...)。"
                "如需切换项目，请同时在本机执行 earthengine authenticate --force。"
            ),
        },
        {
            "key": "year",
            "label": "年份",
            "type": "number",
            "required": True,
            "default": 2025,
            "hint": "用于构建该年度 1—12 月 Sentinel-1 / Sentinel-2 时序合成影像。",
        },
        # ===== 二、研究区（必填，asset / 本地 / 历史 三选一）=====
        {
            "key": "roi_local_path",
            "label": "研究区文件（请打包为 .zip 上传）",
            "type": "file",
            "accept": ".zip,.geojson,.json",
            "kind": "zip",
            "slot": "roi",
            "required": False,
            "hint": (
                "首次运行需上传本地研究区矢量（Shapefile 至少需要 .shp + .shx + .dbf "
                "三件套，请全部打包为 .zip；GeoJSON 也可直接上传）。"
                "后端会自动把首个矢量注册为 GEE Asset 并保存到「已保存 GEE Assets」。"
                "后续运行可直接从历史文件下拉框中选择，或在下方直接填写 GEE Asset ID。"
                "栅格研究区（.tif）请改用下方『研究区 GEE Asset ID』字段，"
                "在 GEE Code Editor 上传后填入。"
            ),
            "xors_with": ["roi_asset_id"],
        },
        {
            "key": "roi_asset_id",
            "label": "研究区 GEE Asset ID（可选，留空则使用上方上传文件）",
            "type": "text",
            "required": False,
            "default": "",
            "hint": (
                "格式：projects/<project>/assets/<name>。"
                "填写后将跳过本地上传，直接复用此 Asset；"
                "提交后会做一次存在/可访问性校验。"
            ),
            "xors_with": ["roi_local_path"],
            "saved_picker": {
                "target_key": "roi_asset_id",
                "label": "查看已保存的研究区 GEE Asset",
                "checkbox_label": "查看已保存的研究区 GEE Asset",
                "endpoint": "/api/algorithms/{algorithm_id}/saved-gee-assets",
                "verify_endpoint": "/api/algorithms/{algorithm_id}/saved-gee-assets/verify",
            },
        },
        # ===== 三、特征文件（必填，asset / 本地 / 历史 三选一）=====
        {
            "key": "samples_local_path",
            "label": "特征文件（CSV / GeoJSON，含样本点与 class 列）",
            "type": "file",
            "accept": ".csv,.geojson,.json",
            "kind": "file",
            "slot": "samples",
            "required": False,
            "hint": (
                "特征文件应为特征生成算法生成的样本特征文件，"
                "首次运行需上传本地 CSV（含 longitude / latitude 与 class 列）或 GeoJSON。"
                "CSV 格式：UTF-8 编码、首行为英文表头、必须包含 longitude 与 latitude 列。"
                "后端会自动把首个矢量注册为 GEE Asset 并保存到「已保存 GEE Assets」。"
                "后续运行可直接从历史文件下拉框中选择，或在下方直接填写 GEE Asset ID。"
            ),
            "xors_with": ["samples_asset_id"],
        },
        {
            "key": "samples_asset_id",
            "label": "特征文件 GEE Asset ID（可选，留空则使用上方上传文件）",
            "type": "text",
            "required": False,
            "default": "",
            "hint": (
                "格式：projects/<project>/assets/<name>。"
                "特征文件应为特征生成算法（time-series-features）输出的样本 FeatureCollection，"
                "必须含 class 列。填写后将跳过本地上传，直接复用此 Asset；"
                "提交后会做一次存在/可访问性校验。"
            ),
            "xors_with": ["samples_local_path"],
            "saved_picker": {
                "target_key": "samples_asset_id",
                "label": "查看已保存的特征文件 GEE Asset",
                "checkbox_label": "查看已保存的特征文件 GEE Asset",
                "endpoint": "/api/algorithms/{algorithm_id}/saved-gee-assets",
                "verify_endpoint": "/api/algorithms/{algorithm_id}/saved-gee-assets/verify",
            },
        },
        # ===== 四、固定参数（仅展示，不可修改）=====
        {
            "key": "__fixed_params_notice__",
            "type": "notice",
            "notice_type": "info",
            "notice_icon": "ℹ️",
            "label": "固定参数（仅展示，不可修改）",
            "hint": (
                f"本算法共输出 {cfg.TOTAL_FEATURE_COUNT} 个特征"
                f"（{cfg.FEATURE_BAND_COUNT} 个波段 × {cfg.TIME_SERIES_MONTHS} 个月 "
                f"+ 1 个 DEM 高程）。\n"
                f"min_values 长度 = {len(cfg.MIN_VALUES)}；"
                f"max_values 长度 = {len(cfg.MAX_VALUES)}；"
                f"DEM 归一化区间 [{cfg.DEM_MIN}, {cfg.DEM_MAX}]；"
                f"Sentinel-2 最大云量 ≤ {cfg.CLOUD_PCT_MAX}%；"
                f"RandomForest 树数 = {cfg.NUM_TREES}；"
                f"训练集比例 = {int(cfg.TRAIN_RATIO * 100)}%。\n"
                "以上参数由算法内置，禁止用户修改；如需调整请修改 configs.py。"
            ),
        },
        # ===== 五、高级参数（默认折叠）=====
        {
            "key": "task_name",
            "label": "GEE 任务名称（留空自动）",
            "type": "text",
            "required": False,
            "default": "",
            "advanced": True,
            "hint": (
                "默认按『CROPClassification_<年份>』自动命名，"
                "后端会自动追加时间戳以避免 GEE Asset 冲突。"
                "本名称会用作下载 GeoTIFF 的文件名（不含时间戳）。"
            ),
        },
        {
            "key": "num_trees",
            "label": "RandomForest 树数",
            "type": "number",
            "required": False,
            "default": cfg.NUM_TREES,
            "advanced": True,
            "hint": f"ee.Classifier.smileRandomForest 的树数量（默认 {cfg.NUM_TREES}）。",
        },
        {
            "key": "train_ratio",
            "label": "训练集比例",
            "type": "number",
            "required": False,
            "default": cfg.TRAIN_RATIO,
            "advanced": True,
            "hint": f"训练集占总样本的比例，区间 (0, 1)；默认 {cfg.TRAIN_RATIO}。",
        },
        {
            "key": "label_property",
            "label": "类别字段名",
            "type": "text",
            "required": False,
            "default": cfg.LABEL_PROPERTY,
            "advanced": True,
            "hint": "样本 FeatureCollection 中保存类别标签的属性名。",
        },
        {
            "key": "cloud_pct_max",
            "label": "Sentinel-2 最大云量 (%)",
            "type": "number",
            "required": False,
            "default": cfg.CLOUD_PCT_MAX,
            "advanced": True,
            "hint": "CLOUDY_PIXEL_PERCENTAGE 阈值，0-100 之间。",
        },
    ]

    def run(
        self,
        params: Dict[str, Any],
        job_dir: str,
        progress_callback: Optional[ProgressCallback] = None,
    ) -> Dict[str, Any]:
        return crop_classification_algorithm.run(params, job_dir, progress_callback)

    def finalize(
        self,
        job: Dict[str, Any],
        job_dir: str,
        progress_callback: Optional[ProgressCallback] = None,
    ) -> Optional[Dict[str, Any]]:
        # Delegate to the algorithm module's finalize() so the dispatcher in
        # job_service._dispatch_finalize can pick it up via getattr(adapter,
        # "finalize"). Same pattern as crop_features.
        return crop_classification_algorithm.finalize(
            job, job_dir, progress_callback=progress_callback
        )