"""GEE crop classification (RandomForest on a labeled FeatureCollection).

Trains a smileRandomForest on the time-series + DEM feature stack, evaluates
via ``errorMatrix`` (Overall Accuracy / Kappa / confusion matrix), classifies
the full ROI and ships the result back to the operator as a GeoTIFF.

Pattern B execution
-------------------
``run()`` immediately returns ``status="submitted"`` with the GEE task id
and the small accuracy metrics (OA / Kappa / confusion matrix). The
background GEE poller in ``app.services.job_service`` watches the task
state and dispatches to :func:`finalize` once GEE reports COMPLETED.
``finalize`` waits for the uploaded Asset to be queryable, downloads the
GeoTIFF into ``job_dir`` via ``geemap.ee_export_image`` so the platform's
``ResultRenderer`` can preview / download it directly, then returns
``status="completed"`` with the file reference.

ROI source
----------
Either:
  * ``roi_local_path``: a local vector file (shp zip / geojson / json)
    auto-ingested into a fresh GEE Asset via
    ``ingest_service.ensure_asset_for_local``;
  * ``roi_asset_id``: an existing ``projects/<project>/assets/<name>``
    Asset — skipped upload, used directly;
  * neither.

Sample-feature file source
-------------------------
Either:
  * ``samples_local_path``: a local CSV with ``longitude`` / ``latitude``
    plus the classification target column (``class`` by default) — auto-
    ingested via ``ingest_service``;
  * ``samples_asset_id``: an existing GEE FeatureCollection Asset;
  * neither.

Fixed parameters
----------------
BAND_NAMES / MIN_VALUES / MAX_VALUES / DEM_MIN / DEM_MAX / CLOUD_PCT_MAX /
NUM_TREES / TRAIN_RATIO / LABEL_PROPERTY live in ``configs.py`` and are
not user-editable on the form. ``num_trees``, ``train_ratio`` and
``label_property`` are surfaced in the collapsed "其他参数" section for
advanced users but default to the hard-coded values.
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import ee

from app.algorithms.base import ProgressCallback, make_card, make_result
from app.algorithms.crop_classification import configs as cfg
from app.services import ingest_service
from app.services.gee_auth import GeeAuthRequired, initialize_ee
from app.storage import job_store


# ---- Module constants -----------------------------------------------------

# Algorithm + slot namespace used by ingest_service's per-(algorithm, slot)
# GEE-asset cache. Keeping the slot names aligned with the front-end's
# ``params_schema`` so the "已上传历史" dropdown + "查看已保存 GEE Assets"
# list both show consistent entries.
_ALGORITHM_ID = "crop_classification"
_ROI_SLOT = "roi"
_SAMPLES_SLOT = "samples"

# GEE asset-export wait / download timeout (seconds).
# Default 10 minutes covers small samples + medium-resolution ROIs in
# ``run()``; finalize() bumps the ceiling to 30 minutes since it runs in
# the background poller thread and is no longer blocking the HTTP request.
_ASSET_WAIT_TIMEOUT = 600.0
_ASSET_WAIT_INTERVAL = 3.0
_DOWNLOAD_TIMEOUT = 600.0
_FINALIZE_WAIT_TIMEOUT = 1800.0


# ---- Helpers --------------------------------------------------------------


def _coerce_label_to_number(feature: ee.Feature, prop: str) -> ee.Feature:
    """Defensive: coerce a sample's ``label_property`` to ``ee.Number``.

    The upstream sample FC (whether uploaded by the user as a CSV / GeoJSON
    or generated by ``crop_features``) may carry the class label with mixed
    types — some rows as Integer ``0`` and others as String ``"10"`` —
    because ``Export.table.toAsset`` preserves the source schema column-by-
    column, and a CSV imported as String stays String even when every cell
    looks numeric. Two distinct GEE crashes come out of this::

        Property 'class' of feature '00000000000000000000': Invalid type.
        Expected type: Float. Actual type: String. Actual value: 10

        Collection.reduceColumns: Cannot compare values '0' (Type:Integer)
        and '10' (Type:String).

    The reliable server-side coercion is to route the property through
    ``ee.String(raw)`` then ``ee.Number.parse(input, radix=10)`` regardless
    of its starting type::

        - Number 0    -> ee.String("0")    -> ee.Number.parse -> 0
        - String "10" -> ee.String("10")   -> ee.Number.parse -> 10
        - null / unparseable -> Number(NaN) -> filtered out later

    ``ee.Number(value)`` directly is unreliable: the Python wrapper raises
    for non-Number inputs and on the server side does NOT uniformly coerce
    String→Number across all GEE versions, which is what surfaces as the
    second error above when a single FC mixes Integer rows with String rows.

    Combined with the ``filter(ee.Filter.notNull(...) + gte(prop, 0))``
    below, this normalises the labels while dropping truly broken rows
    instead of failing the whole job.

    If the source FC does NOT have ``prop`` at all (user uploaded a
    longitude/latitude-only CSV by mistake), the feature is passed through
    unchanged — the ``notNull`` / ``gte`` filter then drops it, and the
    ``n_samples == 0`` guard surfaces a clear Chinese error.
    """
    has_prop = feature.propertyNames().contains(ee.String(prop))
    raw = feature.get(prop)
    return feature.set(
        prop,
        ee.Algorithms.If(
            has_prop,
            ee.Number.parse(ee.String(raw), 10),
            raw,
        ),
    )


def _mask_s2_clouds(image: ee.Image) -> ee.Image:
    """S2 SR cloud mask via QA60 bits 10/11, then scale reflectance.

    Identical to the original standalone script (and to
    ``crop_features.algorithm._mask_s2_clouds``) — kept inline so this
    module remains importable without pulling the feature-extraction
    module's transitive GEE setup.
    """
    qa = image.select("QA60")
    mask = qa.bitwiseAnd(1 << 10).eq(0).And(qa.bitwiseAnd(1 << 11).eq(0))
    return image.updateMask(mask).divide(10000)


def _build_normalize_fn() -> Any:
    """Return a server-side function that maps each band to [0, 1] via min/max.

    Returns a closure because GEE server-side objects (ee.Image.constant)
    can only be created once and reused across calls. Matches the user's
    original ``normalizeDynamic`` definition.
    """
    min_img = ee.Image.constant(cfg.MIN_VALUES).rename(cfg.BAND_NAMES)
    max_img = ee.Image.constant(cfg.MAX_VALUES).rename(cfg.BAND_NAMES)

    def _normalize(img: ee.Image) -> ee.Image:
        return img.subtract(min_img).divide(max_img.subtract(min_img)).clamp(0, 1)

    return _normalize


def _monthly_image(
    m: ee.Number,
    year: int,
    roi_bounds: ee.Geometry,
    normalize: Any,
    cloud_pct_max: int,
) -> ee.Image:
    """Build one month: S2 + S1 → 11 bands → normalized, tagged with 'month'.

    Mirrors ``get_monthly_image`` from the original script verbatim except
    ``cloud_pct_max`` is now a parameter (default unchanged at 80).
    """
    m_int = ee.Number(m)
    start = ee.Date.fromYMD(year, m_int, 1)
    end = start.advance(1, "month")

    s2 = (
        ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
        .filterBounds(roi_bounds)
        .filterDate(start, end)
        .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", cloud_pct_max))
        .map(_mask_s2_clouds)
        .median()
    )

    s1 = (
        ee.ImageCollection("COPERNICUS/S1_GRD")
        .filterBounds(roi_bounds)
        .filterDate(start, end)
        .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VV"))
        .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VH"))
        .filter(ee.Filter.eq("instrumentMode", "IW"))
        .select(["VV", "VH"])
        .median()
    )

    combined = (
        s2.select(["B2", "B3", "B4", "B8", "B11", "B12"])
        .addBands(s2.normalizedDifference(["B8", "B4"]).rename("NDVI"))
        .addBands(
            s2.expression(
                "2.5*((B8-B4)/(B8+6*B4-7.5*B2+1))",
                {
                    "B8": s2.select("B8"),
                    "B4": s2.select("B4"),
                    "B2": s2.select("B2"),
                },
            ).rename("EVI")
        )
        .addBands(s2.normalizedDifference(["B3", "B8"]).rename("NDWI"))
        .addBands(s1)
    )
    return normalize(combined).set("month", m_int)


def _build_time_series_stack(
    year: int,
    roi_bounds: ee.Geometry,
    *,
    cloud_pct_max: int = cfg.CLOUD_PCT_MAX,
) -> ee.Image:
    """12-month normalized stack + DEM, identical to the user's script.

    Reproduces the original ``stackedTimeSeries`` plus ``finalImage``
    (with DEM band appended) pipeline so the trained classifier sees the
    same feature space the upstream time-series feature algorithm
    generates.
    """
    normalize = _build_normalize_fn()
    months = ee.List.sequence(1, cfg.TIME_SERIES_MONTHS)

    monthly = ee.ImageCollection(
        months.map(
            lambda m: _monthly_image(m, year, roi_bounds, normalize, cloud_pct_max)
        )
    )
    annual_median = monthly.median()

    def _fill(img: ee.Image) -> ee.Image:
        img = ee.Image(img)
        m_str = ee.Number(img.get("month")).format("%02d")

        def _rename(b: ee.String) -> ee.String:
            return (
                ee.String(cfg.MONTH_BAND_PREFIX)
                .cat(m_str)
                .cat("_")
                .cat(ee.String(b))
            )

        new_names = img.bandNames().map(_rename)
        return img.unmask(annual_median).rename(new_names)

    filled = monthly.map(_fill)

    def _stack(img: ee.Image, prev: ee.Image) -> ee.Image:
        return ee.Image(prev).addBands(img)

    dummy = ee.Image.constant(0).rename("dummy")
    stacked = ee.Image(filled.iterate(_stack, dummy))
    valid = stacked.bandNames().remove("dummy")
    stacked = stacked.select(valid).unmask(cfg.STACK_NODATA)

    dem = (
        ee.Image("NASA/NASADEM_HGT/001")
        .resample("bilinear")
        .reproject(crs="EPSG:4326", scale=cfg.EXPORT_SCALE)
        .clip(roi_bounds)
    )
    elevation_norm = (
        dem.select("elevation")
        .subtract(cfg.DEM_MIN)
        .divide(cfg.DEM_MAX - cfg.DEM_MIN)
        .clamp(0, 1)
        .rename(cfg.DEM_BAND_NAME)
    )
    return stacked.addBands(elevation_norm)


def _wait_for_asset(asset_id: str, *, timeout: float = _ASSET_WAIT_TIMEOUT) -> None:
    """Poll ``ee.data.getAsset`` until the ingested asset becomes queryable.

    Mirrors the same helper in ``crop_features`` / ``harvest``. ``run()``
    blocks here at most 10 minutes; ``finalize()`` bumps the ceiling.
    """
    deadline = time.monotonic() + timeout
    last_err: Optional[Exception] = None
    while time.monotonic() < deadline:
        try:
            ee.data.getAsset(asset_id)
            return
        except Exception as exc:  # noqa: BLE001
            last_err = exc
            time.sleep(_ASSET_WAIT_INTERVAL)
    raise TimeoutError(
        f"GEE 资产导出超时（>{int(timeout)}s）：{asset_id}; last={last_err}"
    )


def _download_asset_to_local(
    asset_id: str,
    *,
    local_path: str,
    scale: int,
    crs: str,
    region: ee.Geometry,
) -> None:
    """Stream a GEE Asset Image to a local GeoTIFF.

    Wraps ``geemap.ee_export_image`` (which handles both the
    ``getDownloadURL`` fast path for small images and the chunked tiling
    path for large ones). Destination directory is created on demand.
    """
    import geemap  # type: ignore

    out_dir = os.path.dirname(os.path.abspath(local_path))
    os.makedirs(out_dir, exist_ok=True)

    geemap.ee_export_image(
        ee_object=ee.Image(asset_id),
        filename=local_path,
        scale=scale,
        crs=crs,
        region=region,
        file_per_band=False,
    )


def _ingest_local(
    *,
    local_path: Optional[str],
    asset_id: Optional[str],
    slot: str,
    project: str,
    progress_callback: Optional[ProgressCallback] = None,
    progress_tick: Optional[float] = None,
    progress_tick_done: Optional[float] = None,
    label: str,
) -> Optional[List[str]]:
    """Resolve one of the three input modes for an asset-backed parameter.

    Returns one or more GEE asset ids, or ``None`` when neither input was
    provided. A single-element list ``[id]`` means a single Asset; a
    multi-element list means the source file was chunked because GEE's
    ``Export.table.toAsset`` 10 MB cap couldn't fit it in one shot —
    callers must ``ee.FeatureCollection(ids).flatten()`` at use time.

    Precedence:
      1. ``asset_id`` provided → wrap in a one-element list (with one
         ``ee.data.getAsset`` pre-flight check for clear failure messaging).
      2. ``local_path`` provided → auto-ingest via
         ``ingest_service.ensure_asset_for_local`` (idempotent via the
         per-(algorithm, slot) cache) and persist the *first* chunk's id
         to ``job_store`` so the user can re-use it via the front-end
         picker. Known limitation: if the upload was chunked, picking
         this saved asset only loads the first chunk — to get the full
         FC the user should re-submit the same local file (the cache
         returns all chunks).
      3. Neither → return ``None`` (caller emits a precise Chinese error).

    ``label`` is a short user-facing noun ("研究区" / "特征文件") for
    progress messages and error text.
    """
    if asset_id:
        try:
            ee.data.getAsset(asset_id)
        except GeeAuthRequired:
            raise
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                f"无法访问 GEE {label} Asset：{asset_id}。"
                f"请确认 Asset 存在、属于当前项目 ({project})，且您有读取权限。"
                f"原始错误：{exc}"
            ) from exc
        if progress_callback:
            pct = progress_tick_done if progress_tick_done is not None else 15
            progress_callback(pct, f"{label}：复用 {asset_id}")
        return [asset_id]

    if local_path:
        if progress_callback and progress_tick is not None:
            progress_callback(progress_tick, f"{label}：注册本地文件到 GEE Asset")
        try:
            resolved_ids = ingest_service.ensure_asset_for_local(
                local_path=str(local_path),
                slot=slot,
                algorithm=_ALGORITHM_ID,
                project=project,
                kind_hint="feature_collection",
            )
        except GeeAuthRequired:
            raise
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(f"{label}上传到 GEE 失败：{exc}") from exc

        # 自动把刚生成的 Asset ID 持久化到「已保存 GEE Assets」表里，
        # 让用户后续能直接勾选复用，无需再上传本地文件。best-effort：
        # 保存失败不应阻塞算法本身。chunked 上传时只保存第一个 chunk 作为
        # 主入口（picker 后续可扩展为合并多个 chunk）。
        primary_id = resolved_ids[0] if resolved_ids else None
        if primary_id:
            source_name = Path(local_path).name if local_path else ""
            if len(resolved_ids) > 1:
                source_name = (
                    f"{source_name}（已切分为 {len(resolved_ids)} 个 GEE Asset）"
                )
            try:
                job_store.save_gee_asset(
                    asset_id=primary_id,
                    algorithm_id=_ALGORITHM_ID,
                    source_filename=source_name,
                )
            except Exception as exc:  # noqa: BLE001
                print(
                    f"[crop_classification] save_gee_asset failed "
                    f"(asset={primary_id}): {exc}",
                    file=sys.stderr,
                )

        if progress_callback and progress_tick_done is not None:
            progress_callback(progress_tick_done, f"{label}：已注册 {resolved_ids}")
        return resolved_ids

    return None


# ---- Public entry points --------------------------------------------------


def run(
    params: Dict[str, Any],
    job_dir: str,
    progress_callback: Optional[ProgressCallback] = None,
) -> Dict[str, Any]:
    """Build the feature stack, train RandomForest, evaluate, classify, export.

    Pattern B: returns ``status="submitted"`` immediately after submitting
    the GEE Export. The GEE poller in ``job_service`` will detect GEE
    COMPLETED and dispatch to :func:`finalize` to wait for the Asset and
    download the GeoTIFF.
    """
    # ----- 1. GEE init -----
    project = (
        params.get("gee_project_id")
        or params.get("gee_project")
        or os.environ.get("EE_PROJECT")
        or "sodium-ray-505904-i3"
    )
    try:
        initialize_ee(project)
    except GeeAuthRequired as exc:
        return make_result(status="failed", result_type="json", message=str(exc))

    if progress_callback:
        progress_callback(5, "正在连接 GEE")

    # ----- 2. 参数解析 -----
    if "year" not in params or params["year"] in ("", None):
        return make_result(
            status="failed",
            result_type="json",
            message="缺少必填参数：年份（year）。",
        )
    try:
        year = int(params["year"])
    except (TypeError, ValueError):
        return make_result(
            status="failed",
            result_type="json",
            message=f"年份必须是整数：{params['year']!r}",
        )

    num_trees = int(params.get("num_trees", cfg.NUM_TREES))
    train_ratio = float(params.get("train_ratio", cfg.TRAIN_RATIO))
    if not (0.0 < train_ratio < 1.0):
        return make_result(
            status="failed",
            result_type="json",
            message=f"训练集比例必须介于 (0, 1) 之间：{train_ratio}",
        )
    label_property = str(params.get("label_property", cfg.LABEL_PROPERTY)) or cfg.LABEL_PROPERTY
    cloud_pct_max = int(params.get("cloud_pct_max", cfg.CLOUD_PCT_MAX))
    if not (0 <= cloud_pct_max <= 100):
        return make_result(
            status="failed",
            result_type="json",
            message=f"Sentinel-2 最大云量必须在 0~100 之间：{cloud_pct_max}",
        )

    # ----- 3. 研究区解析（asset / 本地 / 历史文件） -----
    try:
        roi_asset_ids = _ingest_local(
            local_path=params.get("roi_local_path"),
            asset_id=(params.get("roi_asset_id") or "").strip() or None,
            slot=_ROI_SLOT,
            project=project,
            progress_callback=progress_callback,
            progress_tick=10,
            progress_tick_done=20,
            label="研究区",
        )
    except GeeAuthRequired as exc:
        return make_result(status="failed", result_type="json", message=str(exc))
    except RuntimeError as exc:
        return make_result(status="failed", result_type="json", message=str(exc))
    except Exception as exc:  # noqa: BLE001
        return make_result(
            status="failed",
            result_type="json",
            message=f"研究区处理失败：{exc}",
        )

    # ----- 4. 样本特征文件解析（asset / 本地 / 历史文件） -----
    try:
        samples_asset_ids = _ingest_local(
            local_path=params.get("samples_local_path"),
            asset_id=(params.get("samples_asset_id") or "").strip() or None,
            slot=_SAMPLES_SLOT,
            project=project,
            progress_callback=progress_callback,
            progress_tick=25,
            progress_tick_done=35,
            label="特征文件",
        )
    except GeeAuthRequired as exc:
        return make_result(status="failed", result_type="json", message=str(exc))
    except RuntimeError as exc:
        return make_result(status="failed", result_type="json", message=str(exc))
    except Exception as exc:  # noqa: BLE001
        return make_result(
            status="failed",
            result_type="json",
            message=f"特征文件处理失败：{exc}",
        )

    if not roi_asset_ids:
        return make_result(
            status="failed",
            result_type="json",
            message=(
                "缺少研究区：请上传本地研究区文件（基本参数区『研究区文件』），"
                "或在下方直接填写 GEE 研究区 Asset ID。"
            ),
        )
    if not samples_asset_ids:
        return make_result(
            status="failed",
            result_type="json",
            message=(
                "缺少特征文件：请上传本地特征文件（基本参数区『特征文件』），"
                "或在下方直接填写 GEE 特征文件 Asset ID。"
                "特征文件应由前面的「特征生成算法」生成。"
            ),
        )

    # chunked 上传会返回多个 asset id；用 flatten() 服务端一次性合并。
    roi = ee.FeatureCollection(roi_asset_ids).flatten()
    roi_bounds = roi.geometry()

    # ----- 5. 构建 12 月时序特征 + DEM -----
    if progress_callback:
        progress_callback(40, "正在构建 12 月 Sentinel-1/2 时序特征 + DEM")

    final_image = _build_time_series_stack(
        year, roi_bounds, cloud_pct_max=cloud_pct_max
    )

    # ----- 5.b 样本点预处理：防御性类型转换 + 清洗 -----
    sample_points = ee.FeatureCollection(samples_asset_ids).flatten()

    # 源样本 FC（用户上传的 CSV/GeoJSON，或 crop_features 生成的产物）中
    # class 列常常是 String（"10"），甚至单 FC 内 Integer 与 String 混存。
    # 下游 ee.Classifier.smileRandomForest 会报
    #   "Property 'class' ... Expected type: Float. Actual type: String"
    # reduceColumns / errorMatrix 会报
    #   "Cannot compare values '0' (Integer) and '10' (String)"
    # 这里统一走 ee.String -> ee.Number.parse(..., 10) 把 label_property
    # 转成数值（数值/字符串都能稳定 parse，NaN 走过滤），并剔除转换失败
    # 的行（class 缺失 / NaN / 负值）。源 FC 完全不含 label_property 列时
    # 不过滤，交给下面的 n_samples==0 检查抛清晰的中文错误。
    sample_points = sample_points.map(
        lambda f: _coerce_label_to_number(f, label_property)
    )
    sample_points = sample_points.filter(ee.Filter.notNull([label_property]))
    sample_points = sample_points.filter(ee.Filter.gte(label_property, 0))

    if progress_callback:
        progress_callback(55, "正在校验样本点 label_property 类型")

    n_samples = sample_points.size().getInfo()
    if not n_samples:
        return make_result(
            status="failed",
            result_type="json",
            message=(
                f"样本点 FeatureCollection 中没有任何有效样本（label_property="
                f"'{label_property}' 缺失或全部为无效数值）。"
                f"请检查上传的样本文件：是否包含 {label_property} 列、"
                f"值是否为有效数字（≥ 0）。原始 Asset：{samples_asset_ids}"
            ),
        )

    feature_bands = final_image.bandNames()

    # ----- 6. 训练 + 验证 -----
    if progress_callback:
        progress_callback(60, f"正在按 {train_ratio:.0%} 划分训练/验证集")

    sample_with_random = sample_points.randomColumn("random")
    training_set = sample_with_random.filter(ee.Filter.lt("random", train_ratio))
    validation_set = sample_with_random.filter(ee.Filter.gte("random", train_ratio))

    if progress_callback:
        progress_callback(
            70, f"正在训练 RandomForest（{num_trees} 棵）并计算混淆矩阵"
        )

    rf_model = ee.Classifier.smileRandomForest(num_trees).train(
        features=training_set,
        classProperty=label_property,
        inputProperties=feature_bands,
    )

    # `getInfo()` of every accuracy number + the confusion matrix so the
    # run() result can ship the small metrics to the UI immediately,
    # without waiting for the toAsset export to land. The same logic as
    # the original standalone script.
    error_matrix = (
        validation_set.classify(rf_model).errorMatrix(label_property, "classification")
    )
    matrix_list = error_matrix.getInfo()
    oa = error_matrix.accuracy().getInfo()
    kappa = error_matrix.kappa().getInfo()

    if progress_callback:
        progress_callback(
            80,
            f"精度评估完成：OA={oa:.4f}，Kappa={kappa:.4f}",
        )

    # ----- 7. 全图分类 + 提交 Export.image.toAsset -----
    if progress_callback:
        progress_callback(85, "正在对全图进行分类并提交 Export.image.toAsset")

    classified = final_image.select(feature_bands).classify(rf_model)

    user_task_name = (
        params.get("task_name") or ""
    ).strip() or f"{cfg.DEFAULT_TASK_PREFIX}_{year}"
    # 时间戳后缀防止 GEE 端 description 冲突（用户在同一年内可能多次提交）。
    unique_description = f"{user_task_name}_{time.strftime('%Y%m%d%H%M%S')}"
    asset_id = f"projects/{project}/assets/{unique_description}"
    output_tif_name = f"{unique_description}.tif"

    task = ee.batch.Export.image.toAsset(
        image=classified.toByte(),
        description=unique_description,
        assetId=asset_id,
        scale=cfg.EXPORT_SCALE,
        crs=cfg.EXPORT_CRS,
        maxPixels=cfg.EXPORT_MAX_PIXELS,
        region=roi.geometry(),
    )
    task.start()
    gee_task_id = getattr(task, "id", None) or task.status().get("id")

    if progress_callback:
        progress_callback(
            95,
            f"已提交 GEE：asset={asset_id}；等待后台 finalize 下载",
        )

    # ----- 8. 返回 submitted（Pattern B） -----
    cards = [
        make_card("task_status", "任务状态", "已提交 GEE", ""),
        make_card("year", "目标年份", year, "年"),
        make_card("overall_accuracy", "总体精度 (OA)", round(oa, 4), ""),
        make_card("kappa", "Kappa 系数", round(kappa, 4), ""),
        make_card("num_trees", "RandomForest 树数", num_trees, ""),
        make_card("train_ratio", "训练集比例", f"{train_ratio:.0%}", ""),
        make_card("gee_task_id", "GEE 任务 ID", gee_task_id or "", ""),
        make_card("asset_id", "GEE 资产", asset_id, ""),
        make_card("output_tif", "输出文件", output_tif_name, ""),
    ]

    return make_result(
        status="submitted",
        result_type="gee_task",
        gee_task_id=gee_task_id,
        progress=10,
        metrics={
            "year": year,
            "oa": oa,
            "kappa": kappa,
            "confusion_matrix": matrix_list,
            "num_trees": num_trees,
            "train_ratio": train_ratio,
            "label_property": label_property,
            "cloud_pct_max": cloud_pct_max,
            "asset_id": asset_id,
            "description": unique_description,
            "output_tif_name": output_tif_name,
            "roi_asset_id": roi_asset_ids[0] if roi_asset_ids else None,
            "roi_asset_ids": list(roi_asset_ids),
            "samples_asset_id": samples_asset_ids[0] if samples_asset_ids else None,
            "samples_asset_ids": list(samples_asset_ids),
            "task_name": user_task_name,
            "cards": cards,
        },
        message=(
            f"GEE 作物分类任务已提交（task_id={gee_task_id}）；"
            f"年份={year}，OA={oa:.4f}，Kappa={kappa:.4f}，"
            f"输出 Asset={asset_id}。"
            f"等待 GEE 端处理完成后由后台自动下载 GeoTIFF。"
        ),
    )


def finalize(
    job: Dict[str, Any],
    job_dir: str,
    progress_callback: Optional[ProgressCallback] = None,
) -> Optional[Dict[str, Any]]:
    """Background finalizer invoked by the GEE poller.

    Steps:
      1. Read ``asset_id`` / ``description`` / ``output_tif_name`` from
         ``job.result.metrics``. Bail with ``None`` if missing.
      2. Wait until the GEE Asset is queryable, up to
         ``_FINALIZE_WAIT_TIMEOUT`` (30 minutes).
      3. Download the Asset as GeoTIFF into ``job_dir/<output_tif_name>``
         via ``geemap.ee_export_image``.
      4. Build and return the new ``make_result`` payload; the poller
         writes it to the job store.

    Raises on any failure so the poller can mark the job as ``failed``
    and surface the error message in the UI.
    """
    result = (job or {}).get("result") or {}
    metrics = result.get("metrics") or {}
    asset_id = metrics.get("asset_id")
    description = metrics.get("description")
    output_tif_name = (
        metrics.get("output_tif_name")
        or (f"{description}.tif" if description else None)
        or "crop_classification.tif"
    )
    if not asset_id or not description:
        return None

    # 重新拿一次 roi_asset_ids 用于下载 region；job.params 可能已被清理，
    # 但 metrics 里已经留了。优先读新格式 (List[str])，回退到旧格式 (str)。
    roi_asset_ids_finalize = metrics.get("roi_asset_ids")
    if not roi_asset_ids_finalize:
        legacy = metrics.get("roi_asset_id") or ""
        roi_asset_ids_finalize = [legacy] if legacy else []
    if not roi_asset_ids_finalize:
        # 没有 region 时退化为输出 asset 整张图的几何范围
        try:
            roi = ee.FeatureCollection(asset_id)
            region = roi.geometry()
        except Exception:
            region = None
    else:
        try:
            roi = ee.FeatureCollection(roi_asset_ids_finalize).flatten()
            region = roi.geometry()
        except Exception:
            region = None

    if progress_callback:
        progress_callback(50, f"等待 GEE Asset 就绪：{asset_id}")

    # Block here is OK — finalize runs in the GEE poller thread, not an
    # HTTP handler. _FINALIZE_WAIT_TIMEOUT (30 min) gives even large
    # tasks room to finish.
    try:
        _wait_for_asset(asset_id, timeout=_FINALIZE_WAIT_TIMEOUT)
    except TimeoutError as exc:
        # 抛出而非返回 failed —— poller 会把 status 翻成 failed 并把 message
        # 写到 job.message，让前端能看到 GEE 任务还在跑、不当成功对待。
        raise

    if progress_callback:
        progress_callback(90, "下载分类结果 GeoTIFF 到本地")

    local_tif_path = os.path.abspath(os.path.join(job_dir, output_tif_name))
    if region is None:
        # 兜底：不带 region 下载（geemap 会用整张图的 footprint）。
        _download_asset_to_local(
            asset_id,
            local_path=local_tif_path,
            scale=cfg.EXPORT_SCALE,
            crs=cfg.EXPORT_CRS,
            region=None,  # type: ignore[arg-type]
        )
    else:
        _download_asset_to_local(
            asset_id,
            local_path=local_tif_path,
            scale=cfg.EXPORT_SCALE,
            crs=cfg.EXPORT_CRS,
            region=region,
        )

    if not os.path.isfile(local_tif_path):
        raise RuntimeError(
            f"GEE 资产下载完成但未找到本地文件：{local_tif_path}。"
            f"请检查 geemap.ee_export_image 输出目录配置。"
        )

    # 写入分类元数据 sidecar —— preview_service 会读这个文件把
    # 10→甘蔗 / 20→水稻 / 30→桉树 / 40→其他作物 / 50→背景 这样的中文标签
    # 暴露到前端图例，而不是只显示“类别 10/20/...”。失败 best-effort：
    # 写不出来也不应该让整次任务失败。
    sidecar_path = os.path.abspath(
        os.path.join(job_dir, output_tif_name + cfg.CLASS_METADATA_SUFFIX)
    )
    sidecar_payload = {
        "schema_version": 1,
        "filename": output_tif_name,
        "class_labels": {str(k): v for k, v in cfg.CLASS_LABELS.items()},
        "class_colors": {str(k): v for k, v in cfg.CLASS_COLORS.items()},
    }
    try:
        with open(sidecar_path, "w", encoding="utf-8") as fh:
            json.dump(sidecar_payload, fh, ensure_ascii=False, indent=2)
    except Exception as exc:  # noqa: BLE001
        print(
            f"[crop_classification] failed to write class metadata sidecar "
            f"({sidecar_path}): {exc}",
            file=sys.stderr,
        )

    size_bytes = os.path.getsize(local_tif_path)

    if progress_callback:
        progress_callback(100, "GEE 作物分类完成")

    # 保留 run() 里拿到的指标 + 加 output 信息 + 重新生成 cards。
    new_cards = [
        make_card("task_status", "任务状态", "完成", ""),
        make_card("year", "目标年份", metrics.get("year", ""), "年"),
        make_card(
            "overall_accuracy",
            "总体精度 (OA)",
            round(metrics.get("oa", 0) or 0, 4),
            "",
        ),
        make_card(
            "kappa", "Kappa 系数", round(metrics.get("kappa", 0) or 0, 4), ""
        ),
        make_card("num_trees", "RandomForest 树数", metrics.get("num_trees", ""), ""),
        make_card(
            "train_ratio",
            "训练集比例",
            f"{(metrics.get('train_ratio') or 0):.0%}" if metrics.get("train_ratio") is not None else "",
            "",
        ),
        make_card(
            "gee_task_id", "GEE 任务 ID", metrics.get("gee_task_id", "") or "", ""
        ),
        make_card("asset_id", "GEE 资产", asset_id, ""),
        make_card("output_tif", "输出文件", output_tif_name, ""),
    ]

    return make_result(
        status="completed",
        result_type="raster",
        files=[
            {
                "name": output_tif_name,
                "label": "classification",
                "path": local_tif_path,
                "size_bytes": size_bytes,
            }
        ],
        metrics={
            **metrics,
            "output_tif": output_tif_name,
            "cards": new_cards,
        },
        message=(
            f"GEE 作物分类完成（task_id={metrics.get('gee_task_id', '')}，"
            f"asset={asset_id}，年份={metrics.get('year', '')}，"
            f"OA={metrics.get('oa', 0):.4f}，Kappa={metrics.get('kappa', 0):.4f}，"
            f"输出 {output_tif_name} {size_bytes} B）"
        ),
    )


__all__ = ["run", "finalize"]